[env:sparkfun_esp32s2_thing_plus_c]
platform = espressif32
board = sparkfun_esp32s2_thing_plus_c
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
